import { Injectable } from '@angular/core';
import { Author } from './author';

@Injectable({
  providedIn: 'root'
})
export class AuthorOperationService {

  authorArr:Author[]=[];

  constructor() { 
  let a1:Author = new Author("Arundhati Roy","Arundhati Roy is an Indian writer, best known for her book The God of Small Things (1997), which won the Man Booker Prize for Fiction in 1997. She was born in Shillong, Meghalaya, India. Her parents were Rajib Roy, a Bengali Hindu tea plantation anager from Calcutta and Mary Roy, a Malayali Syrian Christian women's rights activist from Kerala. When she was two, her parents divorced, and she returned with her mother and brother to Kerala. For some time, the family lived with her maternal grandfather in Ooty, Tamil Nadu. When she was 5, the family moved back to Kerala, where her mother started a school. Roy began writing her first novel, The God of Small Things, in 1992, completing it in 1996. The book is semi-autobiographical in nature. It captures a major part of her childhood experiences in Aymanam. This book gave Arundhati Roy international fame and was also a commercial success. After that she wrote several non-fiction books which includes The End of Imagination (a critique against the Indian government's nuclear policies), The Algebra of Infinite Justice, Listening to Grasshoppers, War Talk and Walking with Comrades. Her second novel, The Ministry of Utmost Happiness, was published in June 2017, 20 years after her first novel. It has been chosen for the Man Booker Prize 2017 Long List. She currently lives in Delhi. ","arundhati.jpg")
    
  
  let a2:Author = new Author("Rk Narayan","Rasipuram Krishnaswami Iyar Narayanaswami otherwise called R. K. Narayan was a twentieth century Indian creator. Conceived on October 10, 1906, in Madras (Chennai), he was the child of a school dean. He spent a large portion of his adolescence under is maternal grandma's supervision and care, as his dad's activity expected him to move from spots to places habitually. Out of weariness, he discovered his mates in a peacock and a monkey. His family generally chatted in English and his grandma dealt with him as well as taught him. She outfitted him with the common astuteness and showed him number juggling, Sanskrit, folklore and traditional Indian music. Also, he went to various schools in Madras, including Lutheran Mission School and C.R.C. Secondary School. Narayan was a ravenous peruser of with an unquenchable craving for the artistic works of Wodehouse, Dickens, Thomas Hardy and Arthur Conan Doyle. As he moved with his dad to Mysore, he exploited the all around supplied library at the school he father educated at. Amid this time, he connected at a college yet neglected to clear the fitness test. Subsequently, Narayan remained at home for an entire year and he dedicated that opportunity to composing and perusing energetically. In the end, he earned a Bachelor degree from Maharaja College of Mysore. Consequent to his brief and frustrating knowledge as an educator, Naryan came to understand that his actual potential lay in composing as opposed to some other field. He composed a book survey of Development of Maritime Laws of seventeenth Century England, which is set apart as his first genuine written work. Sporadically, he composed pieces for English daily papers and magazines. He kept on pursuing composing, despite the fact that his profession did not hold much guarantee in budgetary terms. In the wake of getting hitched to his adored, Narayan found a vocation as a journalist for a daily paper upholding non-Brahmans' rights, The Justice. In 1930, Narayan made an endeavor at novel written work with Swami and Friends. It was his first novel including the anecdotal Malgudi town set in British India. The novel delineates the enterprises of a gathering of youthful schoolboys, disregarding the sociopolitical atmosphere in India under British run the show. Despite the fact that the book is as of late announced as outstanding amongst other English books to be composed by an Indian, it got a large group of dismissal slips when Narayan endeavored to have it distributed the first run through. English essayist, Graham Greene assumed a huge part in the distribution of the book. Thusly, the writer transformed it into a set of three composition spin-offs of the novel.","Rk narayan.jpg");
  
  let a3: Author = new Author(" stephen King","Stephen Edwin King was conceived in Portland, Maine in 1947, the second child of Donald and Nellie Ruth Pillsbury King. After his folks isolated when Stephen was a little child, he and his more established sibling, David, were raised by his mom. Part of his youth were spent in Fort Wayne, Indiana, where his dad's family was at the time, and in Stratford, Connecticut. At the point when Stephen was eleven, his mom took her youngsters back to Durham, Maine, for good. Her folks, Guy and Nellie Pillsbury, had turned out to be crippled with maturity, and Ruth King was convinced by her sisters to assume control over the physical care of the elderly couple. Other relatives gave a little house in Durham and money related help. After Stephen's grandparents passed away, Mrs. Ruler looked for some kind of employment in the kitchens of Pineland, a close-by private office for the simple-minded. Stephen went to the syntax school in Durham and after that Lisbon Falls High School, graduating in 1966. From his sophomore year at the University of Maine at Orono, he composed a week by week segment for the school daily paper, THE MAINE CAMPUS. He was additionally dynamic in understudy governmental issues, filling in as an individual from the Student Senate. He came to help the counter war development on the Orono grounds, touching base at his position from a moderate view that the war in Vietnam was illegal. He moved on from the University of Maine at Orono in 1970, with a B.A. in English and met all requirements to instruct on the secondary school level. A draft board examination instantly post-graduation discovered him 4-F on grounds of hypertension, constrained vision, level feet, and punctured eardrums. Stephen made his first expert short story deal The Glass Floor to Startling Mystery Stories in 1967. All through the early years of his marriage, he kept on pitching stories to men's magazines. A large number of these were later assembled into the Night Shift gathering or showed up in different treasurys","stephen-edwin-king.jpg")
    
  this.authorArr.push(a1);
  this.authorArr.push(a2);
  this.authorArr.push(a3);
}

getAuthorArr():Author[]
{
  return this.authorArr;
}
}
